apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - image: centos:7
    name: mypod
    volumeMounts:
      - name: azure
        mountPath: /var/www/html
    command: ["/bin/bash"]
    tty: true    
  volumes:
  - name: azure
    persistentVolumeClaim:
      claimName: azurefile
